# Generated by Django 2.2 on 2021-03-16 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HTestResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string_A', models.CharField(max_length=200)),
                ('string_B', models.CharField(max_length=200)),
                ('hdistance', models.IntegerField(default=0)),
                ('log_htest', models.DateTimeField(verbose_name='date of test')),
            ],
        ),
    ]
